services:
  php:
    container_name: php-apache
    build:
      context: ./
      target: base
    depends_on:
      - db
    ports: 
      - '8888:80'
    volumes:
      - ./src:/var/www/html/
      - ./config/apache2.conf:/etc/apache2/apache2.conf
    networks:
      - my-network
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: n@mty
      MYSQL_DATABASE: picksome999
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "9906:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: n@mty
    depends_on:
      - db
    networks:
      - my-network
networks:
  my-network:
    driver: bridge

volumes:
  db-data:


  




     