services:
  php:
    container_name: php-apache
    build:
      context: ./
      target: base
    depends_on:
      - db
    ports: 
      - '8000:80'
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    volumes:
      - ./src:/var/www/html
      - ./config/apache2.conf:/etc/apache2/apache2.conf
    networks:
      - my-network
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ww@house
      MYSQL_DATABASE: wwhouse
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin1234
    ports:
      - "9906:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: Admin1234
    depends_on:
      - db
    networks:
      - my-network
networks:
  my-network:
    driver: bridge

volumes:
  db-data:


  




     